# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/camera

PRODUCT_COPY_FILES += \
    vendor/oplus/camera/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml

PRODUCT_PACKAGES += \
    libAPSClient-cmd-jni \
    libAPSClient-jni \
    libAncFilter_jni \
    libAncHumBokeh-jni \
    libAncHumanDoubleExposure-jni \
    libAncHumanRetain-jni_v2 \
    libAncHumanSegFigureFusion-jni \
    libAncHumanVideo-jni \
    libApsFaceBeautyPreviewProductJni \
    libAvatarEngineRender \
    libAvatarEngineRenderNative \
    libCombineLut \
    libCombineLutJni \
    libFileExtender-jni \
    libHeifEncoderWrapper \
    libNativeWinBuffExchange \
    libOplusBlurPreviewJNI \
    libSuperTextWrapper_system_ext \
    libXDocProcessSDK-jni \
    libXDocProcessSDK_system_ext \
    libYTCommon_system_ext \
    libarcsoft_wideselfie \
    libcolorx-loader \
    libcolorx \
    libcoolex \
    libextendfile \
    libjni_wideselfie \
    libjnisingleblur_api \
    libjnistblur_api \
    libmpbase_system_ext \
    liboplusheifwriter \
    libsingle_camera_bokeh_native \
    libst_mobile \
    libst_sticker_jni \
    libarc.ion \
    libtrace \
    OplusAppPlatform \
    OplusCamera \
    oplus-support-wrapper \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk
